## CONTENT 301 REDIRECTIONS

[[redirects]]
  from = "/user-guide/running-rasa-with-docker/"
  to = "/user-guide/docker/building-in-docker/"

[[redirects]]
  from = "/user-guide/running-the-server/"
  to = "/user-guide/configuring-http-api/"

[[redirects]]
  from = "/user-guide/running-rasa-with-docker/#adding-custom-actions"
  to = "/user-guide/how-to-deploy/#deploying-your-action-server"

[[redirects]]
  from = "/user-guide/how-to-deploy/#adding-custom-actions"
  to = "/user-guide/how-to-deploy/#deploying-your-action-server"

[[redirects]]
  from = "/user-guide/how-to-deploy/#using-docker-compose-to-run-multiple-services"
  to = "/user-guide/docker/deploying-in-docker-compose/"

[[redirects]]
  from = "/user-guide/evaluating-models/"
  to = "/user-guide/testing-your-assistant/"

[[redirects]]
  from = "/user-guide/evaluating-models/#end-to-end-evaluation"
  to = "/user-guide/testing-your-assistant/#end-to-end-testing"

[[redirects]]
  from = "/user-guide/installation/"
  to = "/installation/"

[[redirects]]
  from = "/nlu/training-data-format/"
  to = "/nlu-training-data/"

[[redirects]]
  from = "/core/domains/"
  to = "/domain/"

[[redirects]]
  from = "/user-guide/testing-your-assistant/"
  to = "/testing-your-assistant/"

[[redirects]]
  from = "/user-guide/command-line-interface/"
  to = "/command-line-interface/"

[[redirects]]
  from = "/user-guide/setting-up-ci-cd/"
  to = "/setting-up-ci-cd/"

[[redirects]]
  from = "/user-guide/rasa-tutorial/"
  to = "/prototype-an-assistant/"

[[redirects]]
  from = "/user-guide/building-assistants/"
  to = "/chitchat-faqs/"

[[redirects]]
  from = "/core/stories/"
  to = "/stories/"

[[redirects]]
  from = "/user-guide/messaging-and-voice-channels/"
  to = "/messaging-and-voice-channels/"

[[redirects]]
  from = "/user-guide/configuring-http-api/"
  to = "/http-api/"

[[redirects]]
  from = "/user-guide/how-to-deploy/"
  to = "/how-to-deploy/"

[[redirects]]
  from = "/user-guide/cloud-storage/"
  to = "/model-storage/"

[[redirects]]
  from = "/nlu/choosing-a-pipeline/"
  to = "/tuning-your-model/"

[[redirects]]
  from = "/nlu/components/"
  to = "/components/"

[[redirects]]
  from = "/user-guide/connectors/*"
  to = "/connectors/:splat"

[[redirects]]
  from = "/nlu/entity-extraction/"
  to = "/nlu-training-data/"

[[redirects]]
  from = "/core/responses/"
  to = "/domain/#responses"

[[redirects]]
  from = "/core/actions/"
  to = "/actions/"

[[redirects]]
  from = "/core/reminders-and-external-events/"
  to = "/reaching-out-to-user/"

[[redirects]]
  from = "/core/policies/"
  to = "/policies/"

[[redirects]]
  from = "/core/slots/"
  to = "/domain/#slots"

[[redirects]]
  from = "/core/retrieval-actions/"
  to = "/retrieval-actions/"

[[redirects]]
  from = "/core/forms/"
  to = "/forms/"

[[redirects]]
  from = "/core/interactive-learning/"
  to = "/writing-stories/#using-interactive-learning"

[[redirects]]
  from = "/core/fallback-actions/"
  to = "/fallback-handoff/#fallbacks"

[[redirects]]
  from = "/dialogue-elements/small-talk/"
  to = "/chitchat-faqs/"

[[redirects]]
  from = "/api/action-server/"
  to = "/pages/action-server-api/"

[[redirects]]
  from = "/api/http-api/"
  to = "/pages/http-api/"

[[redirects]]
  from = "/api/jupyter-notebooks/"
  to = "/jupyter-notebooks/"

[[redirects]]
  from = "/api/custom-nlu-components/"
  to = "/components/#custom-components"

[[redirects]]
  from = "/api/tracker-stores/"
  to = "/tracker-stores/"

[[redirects]]
  from = "/api/event-brokers/"
  to = "/event-brokers/"

[[redirects]]
  from = "/api/lock-stores/"
  to = "/lock-stores/"

[[redirects]]
  from = "/api/training-data-importers/"
  to = "/training-data-importers/"

[[redirects]]
  from = "/retrieval-actions"
  to = "/chitchat-faqs/"

[[redirects]]
  from = "/prototype-an-assistant"
  to = "/playground/"

# FIXME: this requires some feedback as to the 404, like in the website
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
